const express = require('express')
const path = require('path')
const { showHomePage, index2, index02, index03, index04, indexop, indexop4, indexop3, indexop2, indexop1, restaurant, architecture, photography, landing, resume, models, fitness, about, about2, services, services2, contact, contact2, pricing, careers, login, comingSoon, page404, faq, accordions, alerts, buttons, countdowns, features, forms, grid, col2, col3, col4, shopSIngle, shopCart, shopCheckout } = require('../controllers/pageController')


const router = express.Router()


router.get('/home', showHomePage)
router.get('/index2', index2)
router.get('/index02', index02)
router.get('/index03', index03)
router.get('/index04', index04)
router.get('/indexop', indexop)
router.get('/indexop1', indexop1)
router.get('/indexop2', indexop2)
router.get('/indexop3', indexop3)
router.get('/indexop4', indexop4)
router.get('/restaurant', restaurant)
router.get('/architecture', architecture)
router.get('/photography', photography)
router.get('/landing', landing)
router.get('/resume', resume)
router.get('/models', models)
router.get('/fitness', fitness)
router.get('/about',  about)
router.get('/about2', about2)
router.get('/services', services)
router.get('/services2', services2)
router.get('/contact', contact)
router.get('/contact2', contact2)
router.get('/pricing', pricing)
router.get('/careers', careers)
router.get('/login', login)
router.get('/comingSoon', comingSoon)
router.get('/page404', page404)
router.get('/faq', faq)
router.get('/accordions', accordions)
router.get('/alerts', alerts)
router.get('/buttons', buttons)
router.get('/countdowns', countdowns)
router.get('/features', features)
router.get('/forms', forms)
router.get('/grid', grid)
router.get('/col2', col2)
router.get('/col3', col3)
router.get('/col4', col4)
router.get('/shopSIngle', shopSIngle)
router.get('/shopCart', shopCart)
router.get('/shopCheckout', shopCheckout)



module.exports = router